version: '3.9'
services:
  analysis:
    build:
      context: .
      dockerfile: Dockerfile
    command: python analysis.py
    volumes:
      - ./data:/home/data
      - ./results:/home/results
    privileged: true
